const PORT = process.env.PORT

const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_DEFAULT_KEY
const SUPABASE_AUTH_EMAIL = process.env.SUPABASE_AUTH_EMAIL
const SUPABASE_AUTH_PASSWORD = process.env.SUPABASE_AUTH_PASSWORD

export default {
  PORT,
  SUPABASE_URL,
  SUPABASE_KEY,
  SUPABASE_AUTH_EMAIL,
  SUPABASE_AUTH_PASSWORD,
}
